 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-recreate
  labels:
    app: myapp
spec:
  replicas: 3
  strategy:
    type: Recreate   # delete all old pods first, then create new ones
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:1.19
        ports:
        - containerPort: 80
