# busybox-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
---
# busybox-svc.yml
apiVersion: v1
kind: Service
metadata:
  name: busybox-svc
spec:
  selector:
    app: busybox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
