apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', "echo Init container finished; sleep 2"]
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
