apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: wait-for-busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "Waiting for busybox-pod..."
        until nslookup busybox-pod.default.svc.cluster.local 2>/dev/null; do
          echo "Still waiting..."
          sleep 2
        done
        echo "Busybox pod is up!"

  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
