apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
  - name: demo-container
    image: busybox
    command: ["sh", "-c", "echo '--- ENV FROM ---'; env | grep APP_; echo '--- SINGLE ENV ---'; echo $MY_ENV; echo '--- FILES ---'; cat /etc/config/APP_ENV /etc/config/APP_PORT /etc/config/APP_DEBUG"]
    
    # Way 1: Use entire ConfigMap as environment variables
    envFrom:
    - configMapRef:
        name: my-config

    # Way 2: Use a single key as env var
    env:
    - name: MY_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_ENV

    # Way 3: Mount ConfigMap as files
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config

  volumes:
  - name: config-volume
    configMap:
      name: my-config
