apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values:
                  - production
  containers:
    - name: nginx
      image: nginx
