apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - db
          topologyKey: "kubernetes.io/hostname"   # same node
  containers:
    - name: frontend
      image: nginx
