apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - production   # will only schedule on nodes with env=production
  containers:
  - name: myapp
    image: nginx


# kubectl label node node1 env=testing
# kubectl label node node2 env=production
